config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  root to: "site#home"

  get "site/:slug" => "site#show", as: :show_article

  %w(blog
    history).each do |page|
    get page, to: "site##{page}", as: page
  end

  scope :team do
    %w(team juniors pionirs u12 u10 u8).each do |page|
      get page, to: "team##{page}", as: page
    end
  end

  namespace :admin do
    root to: "interface#index"

    resource :session, controller: 'clearance/sessions', only: [:create]
    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'


    resources :interface, only: [:index]

    resources :articles
    resources :images, only: [:index, :create]

    resources :competitions
    resources :events
    resources :categories
    resources :championships

  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :competition
  belongs_to :category

  has_attachment :home, accept: [:jpg, :jpeg, :gif, :png]
  has_attachment :away, accept: [:jpg, :jpeg, :gif, :png]

  validates :competition, presence: true
  validates :matchday, presence: true
  validates :place, presence: true
  validates :game_date, presence: true
  validates :game_time, presence: true
  validates :home_team, presence: true
  validates :away_team, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController

  def index
    @events = Event.all.page(params[:page]).per_page(20)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to admin_events_path, notice: "Događaj uspješno kreiran!"
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to admin_events_path, notice: "Događaj uspješno spremljen!"
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit(:matchday, :place, :game_date, :game_time, :home_team,
                                  :home, :away_team, :away, :competition_id, :category_id)
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  EVENTS_IMAGE_HELPER = {
      small: { width: 20, height: 20 },
      medium: { width: 70, height: 70, class: "event-logo"},
      large: { width: 500, height: 300 }
    }

  def events_image_tag(event, size)
    image_path = event_image_path(event, size)
    options = EVENTS_IMAGE_HELPER[size]
    cl_image_tag(image_path, options)
  end

  def event_image_path(event, size)
    if event.home.present?
      event.home.path
    else
      nil
    end
  end

  def events_away_tag(event, size)
    image_path = event_away_path(event, size)
    options = EVENTS_IMAGE_HELPER[size]
    cl_image_tag(image_path, options)
  end

  def event_away_path(event, size)
    if event.away.present?
      event.away.path
    else
      nil
    end
  end
end

app/views/admin/events/_form.html.erb
<%= f.collection_select(:category_id, Category.all, :id, :name, prompt: "Odaberi uzrasnu kategoriju", class: "select-wrapper") %>
<%= f.collection_select(:competition_id, Competition.all, :id, :name, prompt: "Odaberi natjecanje", class: "select-wrapper") %>
<%= f.input :matchday %>
<%= f.input :place %>
<%= f.input :game_date, class: "datepicker active", html5: true %>
<%= f.input :game_time %>
<%= f.input :home_team %>
<%= f.input :home, as: :attachinary %>
<%= f.input :away_team %>
<%= f.input :away, as: :attachinary %>

app/views/admin/events/edit.html.erb
<% provide(:title, "Uredi događaj") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Uredi događaj</h1>

    <%= simple_form_for [:admin, @event] do |f| %>
      <%= render "form", f: f %>
      <%= f.button :button, "Spremi promjene" %>
    <% end %>
  </div>
</div>

app/views/admin/events/index.html.erb
<% provide(:title,"Lista događaja") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
  <h1>Lista događaja</h1>
  <%= link_to "Dodaj novi događaj", new_admin_event_path, class: "waves-effect waves-light btn button1" %>
    <table class="highlight bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>Uzrast</th>
          <th>Liga</th>
          <th>Kolo</th>
          <th>Domaćin</th>
          <th>Domaćin logo</th>
          <th>Gost</th>
          <th>Gost logo</th>
          <th>Datum</th>
          <th>Uredi</th>
          <th>Obriši</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.id %></td>
            <td><%= event.category.name if event.category %></td>
            <td><%= event.competition.name if event.competition %></td>
            <td><%= event.matchday %></td>
            <td><%= event.home_team %></td>
            <td><%= events_image_tag(event, :small) %></td>
            <td><%= event.away_team %></td>
            <td><%= events_away_tag(event, :small) %></td>
            <td><%= event.game_date %></td>
            <td><%= link_to edit_admin_event_path(event) do %>
              <i class="material-icons edit-event">mode edit</i>
            <% end %>
            </td>
            <td><%= link_to admin_event_path(event), method: :delete, data: { confirm: "Jeste li sigurni?" }, class: "delete" do %>
              <i class="material-icons">delete</i>
            <% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @events %>

  </div>
</div>

app/views/admin/events/new.html.erb
<% provide(:title, "Novi događaj") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>kreiraj novi događaj</h1>

    <%= simple_form_for [:admin, @event] do |f| %>
      <%= render "form", f: f %>
      <%= f.button :button, "kreiraj događaj" %>
    <% end %>
  </div>
</div>

<%= javascript_include_tag "collection" %>