config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  root to: "site#home"

  get "site/:slug" => "site#show", as: :show_article

  %w(blog
    history).each do |page|
    get page, to: "site##{page}", as: page
  end

  scope :team do
    %w(team juniors pionirs u12 u10 u8).each do |page|
      get page, to: "team##{page}", as: page
    end
  end

  namespace :admin do
    root to: "interface#index"

    resource :session, controller: 'clearance/sessions', only: [:create]
    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'


    resources :interface, only: [:index]

    resources :articles
    resources :images, only: [:index, :create]

    resources :competitions
    resources :events
    resources :categories
    resources :championships

  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_attachment :image, accept: [:jpg, :png, :gif, :jpeg]

  validates :image, presence: true

  validates :title, presence: true
  validates :short_description, presence: true
  validates :body, presence: true
  validates :slug, presence: true

  scope :published, -> { where(published: true) }

  before_validation :generate_slug!

  private

  def generate_slug!
    return if slug.present?
    self.slug = title.parameterize
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController

  def index
    @articles = Article.all.page(params[:page]).per_page(20)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to admin_articles_path, notice: "Članak kreiran!"
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to admin_articles_path, notice: "Izmjene uspješno spremljene!"
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to admin_articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :image, :short_description, :body, :slug, :published, :published_on)
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper

  ARTICLE_IMAGE_OPTIONS = {
    small: { width: 20, height: 20 },
    no_image: { width: 0, height: 0 },
    smallmid: { width: 578, height: 200, class: "smallmid-image" },
    mix: { width: 473, height: 200 },
    medium: { width: 968, height: 350, class: "medium-image"},
    large: { width: 1920, height: 500, class: "large-image" }
  }

  def article_image_tag(article, size)
    image_path = article_image_path(article, size)
    options = ARTICLE_IMAGE_OPTIONS[size]
    cl_image_tag(image_path, options)
  end

  def article_image_path(article, size)
    if article.image.present?
      article.image.path
    else
      nil
    end
  end

  def article_date(article)
    if article.published_on
      article.published_on.strftime("%d-%m-%Y")
    else
      "-"
    end
  end

end

app/views/admin/articles/_form.html.erb
<%= f.input :title %>
<%= f.input :image, as: :attachinary %>
<%= f.input :short_description, wrapper: :vertical_text_input, as: :text %>

<%= f.input :body do %>
  <%= f.input_field :body, as: :text, class: "materialize-textarea text required" %>
  <%= link_to "Markdown help", "http://assemble.io/docs/Cheatsheet-Markdown.html", target: "_blank", class: "pull-right markdown" %>
<% end %>

<% if f.object.persisted? %>
  <%= f.input :slug %>
<% end %>

<%= f.input :published_on, label: false do %>
  Objavljeno
  <%= f.input :published %>
  na
  <%= f.text_field :published_on, placeholder: "Datum", class: "datepicker active", html5: true %>
<% end %>

app/views/admin/articles/edit.html.erb
<% provide(:title, "Uredi članak") %>

<div class="form-wrapper">
  <div class="card-panel hoverable">

    <h1>Uredi članak</h1>

    <%= simple_form_for [:admin, @article] do |f| %>
      <%= render 'form', f: f %>
      <%= f.button :button, "Spremi promjene" %>
    <% end %>
  </div>
</div>

app/views/admin/articles/index.html.erb
<% provide(:title, "Home") %>
<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Lista članaka</h1>
    <%= link_to "Dodaj novi članak", new_admin_article_path, class: "waves-effect waves-light btn button1" %>
    <table class="highlight bordered">
      <thead>
        <tr>
          <th class="t-small">Naslov</th>
          <th class="t-medium">Slug</th>
          <th class="t-small">Slika članka</th>
          <th class="t-medium">Datum</th>
          <th class="t-smass">Objavljeno</th>
          <th>Obriši</th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td><%= link_to article.title, edit_admin_article_path(article) %></td>
            <td><%= article.slug %></td>
            <td><% if article.image.present? %>
              <%= article_image_tag(article, :small) %>
            <% else %>
              <%= article_image_tag(article, :no_image) %>
            <% end %></td>
            <td><%= article_date article %></td>
            <td><%= human_name_for_boolean article.published %></td>
            <td><%= link_to admin_article_path(article), method: :delete, data: { confirm: "Jeste li sigurni?" }, class: "delete" do %>
              <i class="material-icons">delete</i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @articles %>

  </div>
</div>

app/views/admin/articles/new.html.erb
<% provide(:title, "Kreiraj novi članak") %>

<div class="form-wrapper">
  <div class="card-panel hoverable">

    <h1>Kreiraj novi članak</h1>

    <%= simple_form_for [:admin, @article] do |f| %>
      <%= render 'form', f: f %>
      <%= f.button :button, "Kreiraj članak" %>
    <% end %>
  </div>
</div>