config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  root to: "site#home"

  get "site/:slug" => "site#show", as: :show_article

  %w(blog
    history).each do |page|
    get page, to: "site##{page}", as: page
  end

  scope :team do
    %w(team juniors pionirs u12 u10 u8).each do |page|
      get page, to: "team##{page}", as: page
    end
  end

  namespace :admin do
    root to: "interface#index"

    resource :session, controller: 'clearance/sessions', only: [:create]
    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'


    resources :interface, only: [:index]

    resources :articles
    resources :images, only: [:index, :create]

    resources :competitions
    resources :events
    resources :categories
    resources :championships

  end
end

app/models/championship.rb
class Championship < ActiveRecord::Base
  belongs_to :category

  validates :team, presence: true
  validates :goal_difference, presence: true

end

app/controllers/admin/championships_controller.rb
class Admin::ChampionshipsController < Admin::BaseController

  def index
  end

  def new
    @championship = Championship.new
  end

  def create
    @championship = Championship.new(championship_params)

    if @championship.save
      redirect_to admin_championships_path, notice: "Uspješno kreirano!"
    else
      render 'new'
    end
  end

  def edit
    @championship = Championship.find(params[:id])
  end

  def update
    @championship = Championship.find(params[:id])

    respond_to do |format|
      if @championship.update(championship_params)
        format.html { redirect_to(admin_championships_path, notice: "Izmjene spremljenje!")}
      else
        format.html { render "edit" }
      end
    end
  end

  def destroy
    @championship = Championship.find(params[:id])
    @championship.destroy

    redirect_to admin_championships_path
  end


  private

  def championship_params
    params.require(:championship).permit(:team, :games_played, :wins, :draws, :lost, :goal_difference, :points, :category_id)
  end

end

app/helpers/admin/championships_helper.rb
module Admin::ChampionshipsHelper
end

app/views/admin/championships/_form.html.erb
<%= f.collection_select(:category_id, Category.all, :id, :name, prompt: "Odaberi natjecanje", class: "select-wrapper") %>
<%= f.input :team %>

app/views/admin/championships/edit.html.erb
<% provide(:title, "uredi ljestvicu") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Uredi ljestvicu</h1>

    <%= simple_form_for [:admin, @championship] do |f| %>
      <%= render "form", f: f %>
      <%= f.button :button, "Spremi spremi promjene" %>
    <% end %>
  </div>
</div>

app/views/admin/championships/index.html.erb
<% provide(:title,"Natjecanja") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Natjecanja
      <%= link_to "Dodaj novi tim", new_admin_championship_path, class: "waves-effect waves-light btn button1" %></h1>
  </div>
  <div class="row">
    <% Championship.all.order('points DESC').group_by{|champ| champ.category.name}.each do |category, champs| %>
      <div class="col s12 m12 l6">
        <div class="card-panel hoverable">
          <p class="category-name"><%= category %></p>
          <table class="highlight bordered">
            <thead>
              <tr>
                <th>Pos</th>
                <th>Team</th>
                <th>P</th>
                <th>W</th>
                <th>D</th>
                <th>L</th>
                <th>GD</th>
                <th>Pts</th>
                <th>Uredi</th>
                <th>Obriši</th>
              </tr>
            </thead>
            <tbody>
              <% champs.each_with_index do |championship, index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= championship.team %></td>
                  <td><%= best_in_place [:admin, championship], :games_played, as: :input %></td>
                  <td><%= best_in_place [:admin, championship], :wins, as: :input %></td>
                  <td><%= best_in_place [:admin, championship], :draws, as: :input %></td>
                  <td><%= best_in_place [:admin, championship], :lost, as: :input %></td>
                  <td><%= best_in_place [:admin, championship], :goal_difference, as: :input %></td>
                  <td><%= best_in_place [:admin, championship], :points, as: :input %></td>
                  <td><%= link_to edit_admin_championship_path(championship) do %>
                    <i class="material-icons edit-event">mode edit</i>
                  <% end %>
                  </td>
                  <td><%= link_to admin_championship_path(championship), method: :delete, data: { confirm: "Jeste li sigurni?" }, class: "delete" do %>
                    <i class="material-icons">delete</i>
                  <% end %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/championships/new.html.erb
<% provide(:title, "Kreiraj ljestvicu") %>

<div class="create-wrapper">
  <div class="card-panel hoverable">
    <h1>Dodaj novi tim u ljestvicu</h1>

    <%= simple_form_for [:admin, @championship] do |f| %>
      <%= render "form", f: f %>
      <%= f.button :button, "Spremi" %>
    <% end %>
  </div>
</div>