config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  root to: "site#home"

  get "site/:slug" => "site#show", as: :show_article

  %w(blog
    history).each do |page|
    get page, to: "site##{page}", as: page
  end

  scope :team do
    %w(team juniors pionirs u12 u10 u8).each do |page|
      get page, to: "team##{page}", as: page
    end
  end

  namespace :admin do
    root to: "interface#index"

    resource :session, controller: 'clearance/sessions', only: [:create]
    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'


    resources :interface, only: [:index]

    resources :articles
    resources :images, only: [:index, :create]

    resources :competitions
    resources :events
    resources :categories
    resources :championships

  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_attachment :image, accept: [:jpg, :png, :gif, :jpeg]

  validates :image, presence: true

  validates :title, presence: true
  validates :short_description, presence: true
  validates :body, presence: true
  validates :slug, presence: true

  scope :published, -> { where(published: true) }

  before_validation :generate_slug!

  private

  def generate_slug!
    return if slug.present?
    self.slug = title.parameterize
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :events
  has_many :championships

  validates :name, presence: true

end

app/models/championship.rb
class Championship < ActiveRecord::Base
  belongs_to :category

  validates :team, presence: true
  validates :goal_difference, presence: true

end

app/models/competition.rb
class Competition < ActiveRecord::Base
  has_many :events
  has_many :championships

  validates :name, presence: true

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :competition
  belongs_to :category

  has_attachment :home, accept: [:jpg, :jpeg, :gif, :png]
  has_attachment :away, accept: [:jpg, :jpeg, :gif, :png]

  validates :competition, presence: true
  validates :matchday, presence: true
  validates :place, presence: true
  validates :game_date, presence: true
  validates :game_time, presence: true
  validates :home_team, presence: true
  validates :away_team, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base

  OPTIONS_FOR_URL = {
    thumb: {size: "190x190", crop: "thumb" }
  }

  has_attachment :attachment, accept: [:png, :jpg, :jpeg, :gif]

  validates :attachment, presence: true

  delegate :width, :height, to: :attachment

  def url(**options)
    Cloudinary::Utils.cloudinary_url(attachment.path, options)
  end

  def url_for(key)
    options = OPTIONS_FOR_URL.fetch(key)
    url(options)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
    @articles = Article.all.order("published_on DESC").limit(1)
  end

  def blog
    @articles = Article.all.order("published_on DESC").page(params[:page]).per_page(6)
  end

  def show
    @article = Article.find_by_slug!(params[:slug])
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def team

  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper

  ARTICLE_IMAGE_OPTIONS = {
    small: { width: 20, height: 20 },
    no_image: { width: 0, height: 0 },
    smallmid: { width: 578, height: 200, class: "smallmid-image" },
    mix: { width: 473, height: 200 },
    medium: { width: 968, height: 350, class: "medium-image"},
    large: { width: 1920, height: 500, class: "large-image" }
  }

  def article_image_tag(article, size)
    image_path = article_image_path(article, size)
    options = ARTICLE_IMAGE_OPTIONS[size]
    cl_image_tag(image_path, options)
  end

  def article_image_path(article, size)
    if article.image.present?
      article.image.path
    else
      nil
    end
  end

  def article_date(article)
    if article.published_on
      article.published_on.strftime("%d-%m-%Y")
    else
      "-"
    end
  end

end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper

  def human_name_for_boolean(boolean)
    boolean ? "DA" : "NE"
  end

  def admin_menu_items
    [
      ["Početna", admin_root_path],
      ["Početna - Web", root_path]
    ]
  end

  def render_admin_menu
    items = admin_menu_items
    return "" if items.empty?
    lis = items.map do |item|
      li_class = current_page?(item[1]) ? "active" : nil
      link = link_to(item[0], item[1])
      content_tag(:li, link, class: li_class)
    end
    content_tag(:ul, lis.join("").html_safe, class: "right hide-on-med-and-down")
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  EVENTS_IMAGE_HELPER = {
      small: { width: 20, height: 20 },
      medium: { width: 70, height: 70, class: "event-logo"},
      large: { width: 500, height: 300 }
    }

  def events_image_tag(event, size)
    image_path = event_image_path(event, size)
    options = EVENTS_IMAGE_HELPER[size]
    cl_image_tag(image_path, options)
  end

  def event_image_path(event, size)
    if event.home.present?
      event.home.path
    else
      nil
    end
  end

  def events_away_tag(event, size)
    image_path = event_away_path(event, size)
    options = EVENTS_IMAGE_HELPER[size]
    cl_image_tag(image_path, options)
  end

  def event_away_path(event, size)
    if event.away.present?
      event.away.path
    else
      nil
    end
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/admin/interface_helper.rb
module Admin::InterfaceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/login_helper.rb
module LoginHelper

  def current_user_initials
    "#{current_user.first_name.first}#{current_user.last_name.first}".upcase
  end

end

app/helpers/site_helper.rb
module SiteHelper

  def link_to_article(article, text: nil)
    text ||= article.title
    link_to text, "/site/#{article.slug}"
  end

  def main_menu_items
    [
      ["Početna", root_path],
      ["Novosti", blog_path],
      ["Momčad", team_path],
      ["Povijest", history_path]
    ]
  end

  def render_main_menu
    items = main_menu_items
    return "" if items.empty?
    lis = items.map do |item|
      li_class = current_page?(item[1]) ? "active" : nil
      content_tag(:li, link_to(item[0], item[1]), class: li_class)
    end
    content_tag(:ul, lis.join("").html_safe, class: "navigation")
  end

  def md_to_html(text)
    options = {
      hard_wrap: true,
      fenced_code_blocks: true,
      gh_blockcode: true
    }
    extensions = {
      autolink: true,
      no_intra_emphasis: true
    }
    renderer = Redcarpet::Render::HTML.new(options)
    md_for_html= Redcarpet::Markdown.new(renderer, extensions)
    md_for_html.render(text).html_safe
  end

  def team_menu_items
    [
      ["Seniori", team_path],
      ["Juniori", juniors_path],
      ["Pioniri", pionirs_path],
      ["U-12", u12_path],
      ["U-10", u10_path],
      ["U-8", u8_path]
    ]
  end

  def render_team_menu
    items = team_menu_items
    return "" if items.empty?
    lis = items.map do |item|
      li_class = current_page?(item[1]) ? "active" : nil
      content_tag(:li, link_to(item[0], item[1]), class: li_class)
    end
    content_tag(:ul, lis.join("").html_safe, class: "team-nav")
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/admin/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to image_tag("logoMladost.png", class: "admin-logo") %>
    <%= render_admin_menu %>
  </div>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<ul id="slide-out" class="side-nav">
  <li><div class="userView">
      <%= image_tag "admin-background.jpg", class: "admin-background" %>
      <% if signed_in? %>
        <div class="user-initials">
          <span><%= current_user_initials %></span>
        </div>
          <%= link_to "Odjava", sign_out_path, method: :delete, class: "logout" %>
      <% end %>
    </div></li>

    <%= render "layouts/admin/sidebar_menu" %>

</ul>
<a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>

app/views/layouts/admin/_sidebar_menu.html.erb
<li class="<%= 'active' if current_page?(new_admin_article_path) || current_page?(admin_articles_path) %>"><%= link_to "", class: "dropdown-button", "data-activates" => "dropdown-articles" do %>Članci
    <i class="material-icons right">arrow_drop_down</i>
  <% end %>
</li>
<li class="<%= 'active' if current_page?(new_admin_competition_path) || current_page?(admin_competitions_path) %>"><%= link_to "", class: "dropdown-button", "data-activates" => "dropdown-competitions" do %>Natjecanja
    <i class="material-icons right">arrow_drop_down</i>
  <% end %>
</li>
<li class="<%= 'active' if current_page?(new_admin_event_path) || current_page?(admin_events_path) %>"><%= link_to "", class: "dropdown-button", "data-activates" => "dropdown-events" do %>Događaji
    <i class="material-icons right">arrow_drop_down</i>
  <% end %>
</li>
<li class="<%= 'active' if current_page?(new_admin_category_path) || current_page?(admin_categories_path) %>"><%= link_to "", class: "dropdown-button", "data-activates" => "dropdown-categories" do %>Dobne kategorije
    <i class="material-icons right">arrow_drop_down</i>
  <% end %>
</li>
<li class="<%= 'active' if current_page?(new_admin_championship_path) || current_page?(admin_championships_path) %>"><%= link_to "", class: "dropdown-button", "data-activates" => "dropdown-championships" do %>Ljestivce
    <i class="material-icons right">arrow_drop_down</i>
  <% end %>
</li>
<ul id="dropdown-articles" class="dropdown-content">
  <li><%= link_to "Kreiraj članak", new_admin_article_path %></li>
  <li><%= link_to "Lista članaka" , admin_articles_path %></li>
</ul>
<ul id="dropdown-competitions" class="dropdown-content">
  <li><%= link_to "Kreiraj natjecanje", new_admin_competition_path %></li>
  <li><%= link_to "Lista natjecanja", admin_competitions_path %></li>
</ul>
<ul id="dropdown-events" class="dropdown-content">
  <li><%= link_to "Kreiraj događaj", new_admin_event_path %></li>
  <li><%= link_to "Pregled događaja", admin_events_path %></li>
</ul>
<ul id="dropdown-categories" class="dropdown-content">
  <li><%= link_to "Kreiraj dobnu kategoriju", new_admin_category_path %></li>
  <li><%= link_to "Pregled dobnih kategorija", admin_categories_path %></li>
</ul>
<ul id="dropdown-championships" class="dropdown-content">
  <li><%= link_to "Kreiraj ljestvicu", new_admin_championship_path %></li>
  <li><%= link_to "Pregled ljestvica", admin_championships_path %></li>
</ul>